"""empty message

Revision ID: 563e69d2a3f3
Revises: 3dcb5d983adb
Create Date: 2024-05-15 19:17:03.590090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '563e69d2a3f3'
down_revision = '3dcb5d983adb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
